# Copyright 2018 cmheia
from site_utils import log_err, log_info, log_warn

ARTIFACT = 'os_core'

SOURCES = Glob('*.c') + Glob('source/*.c')

# log_warn([s.rstr() for s in SOURCES])

CCFLAGS = env['CCFLAGS']
# log_err(CCFLAGS)
# CCFLAGS = ['-O1' if x == '-O0' else x for x in CCFLAGS]
# log_warn(CCFLAGS)

Lib(ARTIFACT, SOURCES, CCFLAGS=CCFLAGS)
