# Copyright 2018 cmheia
from site_utils import log_err, log_info, log_warn

ARTIFACT = 'os_port'

SOURCES = Glob('*.c')

# log_warn([s.rstr() for s in SOURCES])

CCFLAGS = env['CCFLAGS']
# log_err(CCFLAGS)
CCFLAGS = ['-Os' if x == '-O0' else x for x in CCFLAGS]
# log_warn(CCFLAGS)

Lib(ARTIFACT, SOURCES, CCFLAGS=CCFLAGS)
