# Copyright 2018 cmheia
import os

from site_utils import log_err, log_info, log_warn

# ARTIFACT = os.path.basename(Dir('.').abspath)
ARTIFACT = os.path.basename(os.getcwd())

LWIP_VERSION = '2.0.3'

SOURCES = Glob('api' + LWIP_VERSION + '/*.c') \
    + Glob('lwip' + LWIP_VERSION + '/*.c') \
    + Glob('lwip' + LWIP_VERSION + '/api/*.c') \
    + Glob('lwip' + LWIP_VERSION + '/core/*.c') \
    + Glob('lwip' + LWIP_VERSION + '/core/*/*.c') \
    + Glob('lwip' + LWIP_VERSION + '/netif/*.c')

# log_warn([s.rstr() for s in SOURCES])

Lib(ARTIFACT, SOURCES)
